// Package apimodel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apimodel

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// CreateWatchpartyRequest defines model for CreateWatchpartyRequest.
type CreateWatchpartyRequest struct {
	// CurrentTime (seconds)
	CurrentTime float32 `json:"current_time"`
	Id          string  `json:"id"`
	Lat         float32 `json:"lat"`
	Lon         float32 `json:"lon"`
	Url         string  `json:"url"`
}

// Watchparty defines model for Watchparty.
type Watchparty struct {
	Id  string  `json:"id"`
	Lat float32 `json:"lat"`
	Lon float32 `json:"lon"`

	// PlayTime (seconds)
	PlayTime float32 `json:"play_time"`
	Url      string  `json:"url"`
}

// GetWatchpartyParams defines parameters for GetWatchparty.
type GetWatchpartyParams struct {
	Lat float32 `form:"lat" json:"lat"`
	Lon float32 `form:"lon" json:"lon"`
}

// PostWatchpartyJSONRequestBody defines body for PostWatchparty for application/json ContentType.
type PostWatchpartyJSONRequestBody = CreateWatchpartyRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetWatchparty request
	GetWatchparty(ctx context.Context, params *GetWatchpartyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostWatchpartyWithBody request with any body
	PostWatchpartyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostWatchparty(ctx context.Context, body PostWatchpartyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetWatchparty(ctx context.Context, params *GetWatchpartyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWatchpartyRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWatchpartyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWatchpartyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWatchparty(ctx context.Context, body PostWatchpartyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWatchpartyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetWatchpartyRequest generates requests for GetWatchparty
func NewGetWatchpartyRequest(server string, params *GetWatchpartyParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/watchparty")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lat", runtime.ParamLocationQuery, params.Lat); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lon", runtime.ParamLocationQuery, params.Lon); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostWatchpartyRequest calls the generic PostWatchparty builder with application/json body
func NewPostWatchpartyRequest(server string, body PostWatchpartyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostWatchpartyRequestWithBody(server, "application/json", bodyReader)
}

// NewPostWatchpartyRequestWithBody generates requests for PostWatchparty with any type of body
func NewPostWatchpartyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/watchparty")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetWatchpartyWithResponse request
	GetWatchpartyWithResponse(ctx context.Context, params *GetWatchpartyParams, reqEditors ...RequestEditorFn) (*GetWatchpartyResponse, error)

	// PostWatchpartyWithBodyWithResponse request with any body
	PostWatchpartyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWatchpartyResponse, error)

	PostWatchpartyWithResponse(ctx context.Context, body PostWatchpartyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostWatchpartyResponse, error)
}

type GetWatchpartyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Watchparty
}

// Status returns HTTPResponse.Status
func (r GetWatchpartyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWatchpartyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostWatchpartyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostWatchpartyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostWatchpartyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetWatchpartyWithResponse request returning *GetWatchpartyResponse
func (c *ClientWithResponses) GetWatchpartyWithResponse(ctx context.Context, params *GetWatchpartyParams, reqEditors ...RequestEditorFn) (*GetWatchpartyResponse, error) {
	rsp, err := c.GetWatchparty(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWatchpartyResponse(rsp)
}

// PostWatchpartyWithBodyWithResponse request with arbitrary body returning *PostWatchpartyResponse
func (c *ClientWithResponses) PostWatchpartyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWatchpartyResponse, error) {
	rsp, err := c.PostWatchpartyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWatchpartyResponse(rsp)
}

func (c *ClientWithResponses) PostWatchpartyWithResponse(ctx context.Context, body PostWatchpartyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostWatchpartyResponse, error) {
	rsp, err := c.PostWatchparty(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWatchpartyResponse(rsp)
}

// ParseGetWatchpartyResponse parses an HTTP response from a GetWatchpartyWithResponse call
func ParseGetWatchpartyResponse(rsp *http.Response) (*GetWatchpartyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWatchpartyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Watchparty
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostWatchpartyResponse parses an HTTP response from a PostWatchpartyWithResponse call
func ParsePostWatchpartyResponse(rsp *http.Response) (*PostWatchpartyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostWatchpartyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// watchparty を geo (現在位置) から取得
	// (GET /watchparty)
	GetWatchparty(ctx echo.Context, params GetWatchpartyParams) error
	// watchparty を作成/更新
	// (POST /watchparty)
	PostWatchparty(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetWatchparty converts echo context to params.
func (w *ServerInterfaceWrapper) GetWatchparty(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWatchpartyParams
	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameter("form", true, true, "lat", ctx.QueryParams(), &params.Lat)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lat: %s", err))
	}

	// ------------- Required query parameter "lon" -------------

	err = runtime.BindQueryParameter("form", true, true, "lon", ctx.QueryParams(), &params.Lon)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lon: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWatchparty(ctx, params)
	return err
}

// PostWatchparty converts echo context to params.
func (w *ServerInterfaceWrapper) PostWatchparty(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostWatchparty(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/watchparty", wrapper.GetWatchparty)
	router.POST(baseURL+"/watchparty", wrapper.PostWatchparty)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6yUwW7TQBCGX8UaOLSSVbvQQ+UbRYAqBFQFiUMVoa09Tbaydzez4yIr8oGeQAgVcSgH",
	"+gCcEAeu6cukSV8D7TrgREmQinpLZtf/zP/NzA4g1YXRChVbSAZg0x4Wwv98SCgYXwtOe0YQV/vYL9Gy",
	"OzKkDRJL9BfTkggVv2FZoPufoU1JGpZaQQJrFlOtMrsOIXBlEBJQZXGIBHUIMnMfTMOWSaquC+eCZ+Lt",
	"9dwpLomXlC/RqUMg7JeSMIPkwOVqbobzFTfpGvHO3xr14TGm7MRbAovWb6l+k4vqf/Dd1Heb59+mnYRU",
	"R9qLS87d2bMq2H/08lXwYG8XQjhBsk2BmxvxRuyK0QaVMBISuO9DIRjBPY8pejvHsIsejwMpnM3dDBJ4",
	"gjxD2n1MokBGspAcDEC6XP0SyZ0p4VBNLbRemUoMpyO8hHMdrpDR6kYyHXfZGq1sMwT34tivgVaMyjsT",
	"xuQy9d6iY9s0vdW7S3gECdyJ2tWLpnsXzSDwXZgfhhdPHeiteGtxTp5rDh7rUmW+/7YsCkEVJNCSD0an",
	"X4Iu6mDt+uxyfPH9avjpevhjPRi9+zg6/TA+Ox9ffvXDqO2S9uxpO98fap6DHZ1Vt+Z+1ZNTz8+0a1C9",
	"0ITNRSiNXtZAixfPd0QWtDlWY7saXkzef44m335Nzn821Vikkz+z6dcQeswmiaJcpyLvacvJdrwdQ92p",
	"fwcAAP//NVi7B2QFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
